//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NafanyaVPN.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NafanyaVPN.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Скачайте и установите на устройство приложение Outline:
        ///
        ///iOS: https://itunes.apple.com/app/outline-app/id1356177741
        ///
        ///macOS: https://itunes.apple.com/app/outline-app/id1356178125
        ///
        ///Windows: https://s3.amazonaws.com/outline-releases/client/windows/stable/Outline-Client.exe
        ///
        ///Linux: https://s3.amazonaws.com/outline-releases/client/linux/stable/Outline-Client.AppImage
        ///
        ///Android: https://play.google.com/store/apps/details?id=org.outline.android.client
        ///
        ///Дополнительная ссылка для Android: https://s3.am [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OutlineInstruction {
            get {
                return ResourceManager.GetString("OutlineInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Вас приветствует бот Нафаня!&lt;/b&gt;
        ///При пополнении счёта подписка активируется автоматически.
        ///Если хотите контроллировать этот процесс самостоятельно, то
        ///можете отключить автоматическое продление в настройках.
        ///Подписка оформляется на &lt;b&gt;%subscriptionLength%&lt;/b&gt; с момента активации,
        ///стоимость составляет &lt;b&gt;%subscriptionCost%&lt;/b&gt;..
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
    }
}
